# Generated by Django 5.1.6 on 2025-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('gym_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
