# Generated by Django 5.1.6 on 2025-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gymvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymvisit',
            name='exit_time',
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='gym_busy_rating',
            field=models.IntegerField(choices=[(0, '0% (Empty)'), (1, '25% (Low Crowd)'), (2, '50% (Medium Crowd)'), (3, '75% (High Crowd)'), (4, '100% (Full)')], default=0),
            preserve_default=False,
        ),
    ]
